language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
  - "C:\Users\VASS\.m2/repository"
  - "C:\Users\VASS\.sonar/cache"
addons: 
  sonarqube:
    organization: NICOH
install:
- mvn dependency:go-offline
script:
- mvn verify site sonar:sonar -Dmaven.test.failure.ignore=true
